version: '3.7'

services:
  springboot:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - shared-net
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
       - dbdata:/data/db
    networks:
      - shared-net

volumes:
  dbdata:

networks:
  shared-net:
    driver: bridge
