version: '3.7'

services:
  springboot:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    networks:
      - shared-net
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - shared-net

volumes:
  postgres:

networks:
  shared-net:
    driver: bridge
