spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/qryptic_prod
    username: postgres
    password: test1234

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false